### ISSUE TITLE
passing unnecessary args to a function/method

### ISSUE THREAD

**Issue by nesnoj** [openego/dingo#8]
Example in class [MVGridDingo](https://github.com/openego/dingo/blob/dev/dingo/core/network/grids.py#L95-L96): Here 2 args are passed that can be easily obtained within the method _parametrize_lines_ instead. Which is the appropriate way?

Args are obtained within method instead:
**Pros:** Clearer code
**Cons:** No documentation for the arguments within docstring

**Comment by MGlauer** [comment]
This highly depends on whether the method should be called with parameter other than the `self.region.peak_load` and `self.region.geo_data.area`. 

If *yes*: Everything is fine. But: both methods contain `self.region`. Hence, it might be possible that both parameters origin from different regions, i.e. 
`parametrize_lines(regionA.peak_load, regionB.geo_data.area)'
Is this a use case? You might want to pass the region object instead of both attributes.

If *no*: This method does not need any parameters.

**Comment by nesnoj** [comment]
Thank you for your reply Martin, good to know you're on the watchlist! :)
Actually, different regions are not a use case so I'd go as well for the no-parameters-way..
